{% set name = "gwdatafind" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37bd2375771587d2bb72b9df8f1b0e6fb7d90205ea903cc92a654b28561b34f3
  patches:
    - man-colon.patch

build:
  entry_points:
    - gw_data_find = gwdatafind.__main__:main
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - mkdir -p ${PREFIX}/man/man1
    - argparse-manpage
          --description "discover available GW data"
          --function command_line
          --module gwdatafind.__main__
          --output ${PREFIX}/man/man1/gw_data_find.1
          --prog gw_data_find
          --project-name {{ name }}
          --version {{ version }}

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    # for the man pages
    - argparse-manpage
    - igwn-auth-utils >=0.3.1
    - ligo-segments
  run:
    - igwn-auth-utils >=0.3.1
    - ligo-segments
    - python >=3.6
  run_constrained:
    # pin to lscsoft-glue-2.0.0 to prevent file clobbering
    - lscsoft-glue >=2.0.0

test:
  requires:
    - pip
    - pytest
    - requests-mock
  commands:
    # check metadata
    - python -m pip check gwdatafind
    - python -m pip show gwdatafind
    # run test suite
    - python -m pytest --pyargs gwdatafind
    # check entry points
    - python -m gwdatafind --help
    - gw_data_find --help
    # check man pages
    - man -w gw_data_find
    - man -Pcat gw_data_find

about:
  home: https://gwdatafind.readthedocs.io
  doc_url: https://gwdatafind.readthedocs.io
  dev_url: https://git.ligo.org/gwdatafind/gwdatafind
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: The client library for the LIGO Data Replicator (LDR) service.
  description: |
    The DataFind service allows users to query for the location of
    Gravitational-Wave Frame (GWF) files containing data from the current
    gravitational-wave detectors.

extra:
  recipe-maintainers:
    - duncanmmacleod
