{% set name = "gwdatafind" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb97eebc5d89c5be4d9db53496f9ad0e2fd0496d99ea2cd4fc3e543674b48da3
  patches:
    # remove unused requirements
    - requirements.patch

build:
  entry_points:
    - gw_data_find = gwdatafind.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - ligo-segments
    - pyopenssl
    - python >=3.6
  run_constrained:
    # pin to lscsoft-glue-2.0.0 to prevent file clobbering
    - lscsoft-glue >=2.0.0

test:
  requires:
    - pip
    - pytest
  commands:
    # check metadata
    - python -m pip check
    # run test suite
    - python -m pytest --pyargs gwdatafind
    # check entry points
    - python -m gwdatafind --help
    - gw_data_find --help

about:
  home: https://gwdatafind.readthedocs.io
  doc_url: https://gwdatafind.readthedocs.io
  dev_url: https://git.ligo.org/gwdatafind/gwdatafind
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: The client library for the LIGO Data Replicator (LDR) service.
  description: |
    The DataFind service allows users to query for the location of
    Gravitational-Wave Frame (GWF) files containing data from the current
    gravitational-wave detectors.

extra:
  recipe-maintainers:
    - duncanmmacleod
