{% set name = "gwdatafind" %}
{% set version = "1.0.1" %}
{% set sha256 = "459e860749bc9b2c910106c1d0d1ff19210d526c8e7536978f40e655f5d55b9d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - pyopenssl
    - ligo-segments

test:
  requires:
    - pytest
    - mock  # [py2k]
  imports:
    - gwdatafind.http
    - gwdatafind.ui
    - gwdatafind.utils
  commands:
    - python -m pytest --pyargs gwdatafind
    - python -m gwdatafind --help

about:
  home: https://gwdatafind.readthedocs.io
  doc_url: https://gwdatafind.readthedocs.io
  dev_url: https://git.ligo.org/lscsoft/{{ name }}
  license: GPLv3
  license_file: LICENSE
  license_family: GPL
  summary: The client library for the LIGO Data Replicator (LDR) service.
  description: |
    The DataFind service allows users to query for the location of
    Gravitational-Wave Frame (GWF) files containing data from the current
    gravitational-wave detectors.

extra:
  recipe-maintainers:
    - duncanmmacleod
