{% set name = "gwdatafind" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b7b586a2fbe87dc3867c38699c50ad8028f8403a6689b21ac6229e0ac127492

build:
  entry_points:
    - gw_data_find = gwdatafind.__main__:main
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - pyopenssl
    - ligo-segments
  run_constrained:
    # pin to lscsoft-glue-2.0.0 to prevent file clobbering
    - lscsoft-glue >=2.0.0

test:
  requires:
    - pytest
  imports:
    - gwdatafind.http
    - gwdatafind.ui
    - gwdatafind.utils
  commands:
    - python -m pytest --pyargs gwdatafind
    - python -m gwdatafind --help
    - gw_data_find --help

about:
  home: https://gwdatafind.readthedocs.io
  doc_url: https://gwdatafind.readthedocs.io
  dev_url: https://git.ligo.org/gwdatafind/gwdatafind
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: The client library for the LIGO Data Replicator (LDR) service.
  description: |
    The DataFind service allows users to query for the location of
    Gravitational-Wave Frame (GWF) files containing data from the current
    gravitational-wave detectors.

extra:
  recipe-maintainers:
    - duncanmmacleod
