{% set name = "gwdatafind" %}
{% set version = "1.0.4" %}
{% set sha256 = "3b7b586a2fbe87dc3867c38699c50ad8028f8403a6689b21ac6229e0ac127492" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - pyopenssl
    - ligo-segments
  run_constrained:
    # pin to lscsoft-glue-2.0.0 to prevent file clobbering
    - lscsoft-glue >=2.0.0

test:
  requires:
    - pytest
    - mock  # [py2k]
  imports:
    - gwdatafind.http
    - gwdatafind.ui
    - gwdatafind.utils
  commands:
    - python -m pytest --pyargs gwdatafind
    - python -m gwdatafind --help

about:
  home: https://gwdatafind.readthedocs.io
  doc_url: https://gwdatafind.readthedocs.io
  dev_url: https://git.ligo.org/lscsoft/{{ name }}
  license: GPLv3
  license_file: LICENSE
  license_family: GPL
  summary: The client library for the LIGO Data Replicator (LDR) service.
  description: |
    The DataFind service allows users to query for the location of
    Gravitational-Wave Frame (GWF) files containing data from the current
    gravitational-wave detectors.

extra:
  recipe-maintainers:
    - duncanmmacleod
