travis:
  secure:
    BINSTAR_TOKEN: boeo9nZTa5pJB42Q0lfZxCtVvQbFI3IAu9wyfz0QVTeE70JXxDsm7+oJZ+XJV0U2FaxOYL3REoqhKF9TwqNzZP7JeDf9vdzSzVrPn2CdJKOLti/nwbVlZIPJiz93xfSyl2mgPDFmenzjOGZjckZJlH54WXEzSuKpmovI1pZwGTE4Td9rwQ6mT9Kt8kdgRuLP0WibrNrYn60nILcuOKnAorn+38dKGlJyMuiJaeTcHdvbgZPHmAqv1gZrICYNIeC0qcaMl/aMJm7oszubPKVxsYs8NCc+kqicnCyfTyuZDy4pJ30yTR06ntkQ117OGZHpxa9oT8561ZjHUWSS+raH/JbKYp0uN+BAbY7iuuSf9ZZ0+03Ag5NkAyFeaY95D4tr3M4U/draPg4o2E2exvua1jO27RBgKsG0sAaVned5Z0egbkHxRb5nyyx0PH1r0WeRvMEnmi0DcILxl5huZ+lzXAzwuFJdYRIljtr+dcneBzq5P1MCYxIAasi9lqv5Wp8VrzbNrEmulFd5wxDOgnFXnDydDBSSa6IySvxptfOmy8LRANwTlIeyzqoB0WEUzffY3Y1x5US/2z5+nYi9CdUlirirmwIKXz/a0BfzY6uVc3zzS4juakA59ZkwWwN8YDKY8x3iwzYS0aK/gJW26m488lLSitP2Derk6Z3WxJL6G1E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
